/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createEvaluateResponseFromDiscriminatorValue, serializeEvaluateRequest, serializeEvaluateResponse, type EvaluateRequest, type EvaluateResponse } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/intent/evaluate
 */
export interface EvaluateRequestBuilder extends BaseRequestBuilder<EvaluateRequestBuilder> {
    /**
     * Evaluate intent against policy
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<EvaluateResponse>}
     */
     post(body: EvaluateRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<EvaluateResponse | undefined>;
    /**
     * Evaluate intent against policy
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: EvaluateRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const EvaluateRequestBuilderUriTemplate = "{+baseurl}/api/intent/evaluate";
/**
 * Metadata for all the requests in the request builder.
 */
export const EvaluateRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: EvaluateRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createEvaluateResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeEvaluateRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
