/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { BehaviorRequestBuilderNavigationMetadata, type BehaviorRequestBuilder } from './behavior/index.js';
// @ts-ignore
import { IntentRequestBuilderNavigationMetadata, type IntentRequestBuilder } from './intent/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api
 */
export interface ApiRequestBuilder extends BaseRequestBuilder<ApiRequestBuilder> {
    /**
     * The behavior property
     */
    get behavior(): BehaviorRequestBuilder;
    /**
     * The intent property
     */
    get intent(): IntentRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ApiRequestBuilderUriTemplate = "{+baseurl}/api";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ApiRequestBuilderNavigationMetadata: Record<Exclude<keyof ApiRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    behavior: {
        navigationMetadata: BehaviorRequestBuilderNavigationMetadata,
    },
    intent: {
        navigationMetadata: IntentRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
