/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createTimelineResponseFromDiscriminatorValue, type TimelineResponse } from '../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/intent/analytics/timeline/{entityId}
 */
export interface WithEntityItemRequestBuilder extends BaseRequestBuilder<WithEntityItemRequestBuilder> {
    /**
     * Get intent timeline for an entity
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<TimelineResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<TimelineResponse | undefined>;
    /**
     * Get intent timeline for an entity
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithEntityItemRequestBuilderUriTemplate = "{+baseurl}/api/intent/analytics/timeline/{entityId}";
/**
 * Metadata for all the requests in the request builder.
 */
export const WithEntityItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: WithEntityItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createTimelineResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
