// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ApiSdk.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum EvaluateResponse_decision
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Allow")]
        #pragma warning disable CS1591
        Allow,
        #pragma warning restore CS1591
        [EnumMember(Value = "Observe")]
        #pragma warning disable CS1591
        Observe,
        #pragma warning restore CS1591
        [EnumMember(Value = "Warn")]
        #pragma warning disable CS1591
        Warn,
        #pragma warning restore CS1591
        [EnumMember(Value = "Block")]
        #pragma warning disable CS1591
        Block,
        #pragma warning restore CS1591
        [EnumMember(Value = "Escalate")]
        #pragma warning disable CS1591
        Escalate,
        #pragma warning restore CS1591
        [EnumMember(Value = "RequireAuth")]
        #pragma warning disable CS1591
        RequireAuth,
        #pragma warning restore CS1591
        [EnumMember(Value = "RateLimit")]
        #pragma warning disable CS1591
        RateLimit,
        #pragma warning restore CS1591
    }
}
