/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createExplainResponseFromDiscriminatorValue, serializeExplainRequest, serializeExplainResponse, type ExplainRequest, type ExplainResponse } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/intent/explain-tree
 */
export interface ExplainTreeRequestBuilder extends BaseRequestBuilder<ExplainTreeRequestBuilder> {
    /**
     * Get decision tree explanation for intent
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ExplainResponse>}
     */
     post(body: ExplainRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ExplainResponse | undefined>;
    /**
     * Get decision tree explanation for intent
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: ExplainRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ExplainTreeRequestBuilderUriTemplate = "{+baseurl}/api/intent/explain-tree";
/**
 * Metadata for all the requests in the request builder.
 */
export const ExplainTreeRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: ExplainTreeRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createExplainResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeExplainRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
