/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { CompareRequestBuilderRequestsMetadata, type CompareRequestBuilder } from './compare/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/intent/playground
 */
export interface PlaygroundRequestBuilder extends BaseRequestBuilder<PlaygroundRequestBuilder> {
    /**
     * The compare property
     */
    get compare(): CompareRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const PlaygroundRequestBuilderUriTemplate = "{+baseurl}/api/intent/playground";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const PlaygroundRequestBuilderNavigationMetadata: Record<Exclude<keyof PlaygroundRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    compare: {
        requestsMetadata: CompareRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
