// <auto-generated/>
#pragma warning disable CS0618
using ApiSdk.Api.Intent.Analytics;
using ApiSdk.Api.Intent.Evaluate;
using ApiSdk.Api.Intent.ExplainTree;
using ApiSdk.Api.Intent.Infer;
using ApiSdk.Api.Intent.Playground;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace ApiSdk.Api.Intent
{
    /// <summary>
    /// Builds and executes requests for operations under \api\intent
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class IntentRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The analytics property</summary>
        public global::ApiSdk.Api.Intent.Analytics.AnalyticsRequestBuilder Analytics
        {
            get => new global::ApiSdk.Api.Intent.Analytics.AnalyticsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The evaluate property</summary>
        public global::ApiSdk.Api.Intent.Evaluate.EvaluateRequestBuilder Evaluate
        {
            get => new global::ApiSdk.Api.Intent.Evaluate.EvaluateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The explainTree property</summary>
        public global::ApiSdk.Api.Intent.ExplainTree.ExplainTreeRequestBuilder ExplainTree
        {
            get => new global::ApiSdk.Api.Intent.ExplainTree.ExplainTreeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The infer property</summary>
        public global::ApiSdk.Api.Intent.Infer.InferRequestBuilder Infer
        {
            get => new global::ApiSdk.Api.Intent.Infer.InferRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The playground property</summary>
        public global::ApiSdk.Api.Intent.Playground.PlaygroundRequestBuilder Playground
        {
            get => new global::ApiSdk.Api.Intent.Playground.PlaygroundRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Api.Intent.IntentRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public IntentRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/intent", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Api.Intent.IntentRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public IntentRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/intent", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
