/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { TimelineRequestBuilderNavigationMetadata, type TimelineRequestBuilder } from './timeline/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/intent/analytics
 */
export interface AnalyticsRequestBuilder extends BaseRequestBuilder<AnalyticsRequestBuilder> {
    /**
     * The timeline property
     */
    get timeline(): TimelineRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const AnalyticsRequestBuilderUriTemplate = "{+baseurl}/api/intent/analytics";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const AnalyticsRequestBuilderNavigationMetadata: Record<Exclude<keyof AnalyticsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    timeline: {
        navigationMetadata: TimelineRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
