/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { AnalyticsRequestBuilderNavigationMetadata, type AnalyticsRequestBuilder } from './analytics/index.js';
// @ts-ignore
import { EvaluateRequestBuilderRequestsMetadata, type EvaluateRequestBuilder } from './evaluate/index.js';
// @ts-ignore
import { ExplainTreeRequestBuilderRequestsMetadata, type ExplainTreeRequestBuilder } from './explainTree/index.js';
// @ts-ignore
import { InferRequestBuilderRequestsMetadata, type InferRequestBuilder } from './infer/index.js';
// @ts-ignore
import { PlaygroundRequestBuilderNavigationMetadata, type PlaygroundRequestBuilder } from './playground/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/intent
 */
export interface IntentRequestBuilder extends BaseRequestBuilder<IntentRequestBuilder> {
    /**
     * The analytics property
     */
    get analytics(): AnalyticsRequestBuilder;
    /**
     * The evaluate property
     */
    get evaluate(): EvaluateRequestBuilder;
    /**
     * The explainTree property
     */
    get explainTree(): ExplainTreeRequestBuilder;
    /**
     * The infer property
     */
    get infer(): InferRequestBuilder;
    /**
     * The playground property
     */
    get playground(): PlaygroundRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const IntentRequestBuilderUriTemplate = "{+baseurl}/api/intent";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const IntentRequestBuilderNavigationMetadata: Record<Exclude<keyof IntentRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    analytics: {
        navigationMetadata: AnalyticsRequestBuilderNavigationMetadata,
    },
    evaluate: {
        requestsMetadata: EvaluateRequestBuilderRequestsMetadata,
    },
    explainTree: {
        requestsMetadata: ExplainTreeRequestBuilderRequestsMetadata,
    },
    infer: {
        requestsMetadata: InferRequestBuilderRequestsMetadata,
    },
    playground: {
        navigationMetadata: PlaygroundRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
