/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createCompareResponseFromDiscriminatorValue, serializeCompareRequest, serializeCompareResponse, type CompareRequest, type CompareResponse } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/intent/playground/compare
 */
export interface CompareRequestBuilder extends BaseRequestBuilder<CompareRequestBuilder> {
    /**
     * Compare intent models in playground
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<CompareResponse>}
     */
     post(body: CompareRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<CompareResponse | undefined>;
    /**
     * Compare intent models in playground
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: CompareRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const CompareRequestBuilderUriTemplate = "{+baseurl}/api/intent/playground/compare";
/**
 * Metadata for all the requests in the request builder.
 */
export const CompareRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: CompareRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createCompareResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeCompareRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
