// <auto-generated/>
#pragma warning disable CS0618
using ApiSdk.Api.Intent.Playground.Compare;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace ApiSdk.Api.Intent.Playground
{
    /// <summary>
    /// Builds and executes requests for operations under \api\intent\playground
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PlaygroundRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The compare property</summary>
        public global::ApiSdk.Api.Intent.Playground.Compare.CompareRequestBuilder Compare
        {
            get => new global::ApiSdk.Api.Intent.Playground.Compare.CompareRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Api.Intent.Playground.PlaygroundRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PlaygroundRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/intent/playground", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Api.Intent.Playground.PlaygroundRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PlaygroundRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/intent/playground", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
