// <auto-generated/>
#pragma warning disable CS0618
using ApiSdk.Api.Intent.Analytics.Timeline.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace ApiSdk.Api.Intent.Analytics.Timeline
{
    /// <summary>
    /// Builds and executes requests for operations under \api\intent\analytics\timeline
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TimelineRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the ApiSdk.api.intent.analytics.timeline.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::ApiSdk.Api.Intent.Analytics.Timeline.Item.WithEntityItemRequestBuilder"/></returns>
        public global::ApiSdk.Api.Intent.Analytics.Timeline.Item.WithEntityItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("entityId", position);
                return new global::ApiSdk.Api.Intent.Analytics.Timeline.Item.WithEntityItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Api.Intent.Analytics.Timeline.TimelineRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TimelineRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/intent/analytics/timeline", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Api.Intent.Analytics.Timeline.TimelineRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TimelineRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/intent/analytics/timeline", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
