/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithEntityItemRequestBuilder, WithEntityItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/intent/analytics/timeline
 */
export interface TimelineRequestBuilder extends BaseRequestBuilder<TimelineRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.api.intent.analytics.timeline.item collection
     * @param entityId Unique identifier of the item
     * @returns {WithEntityItemRequestBuilder}
     */
     byEntityId(entityId: string) : WithEntityItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const TimelineRequestBuilderUriTemplate = "{+baseurl}/api/intent/analytics/timeline";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const TimelineRequestBuilderNavigationMetadata: Record<Exclude<keyof TimelineRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byEntityId: {
        requestsMetadata: WithEntityItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["entityId"],
    },
};
/* tslint:enable */
/* eslint-enable */
