// <auto-generated/>
#pragma warning disable CS0618
using ApiSdk.Api.Behavior.Space;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace ApiSdk.Api.Behavior
{
    /// <summary>
    /// Builds and executes requests for operations under \api\behavior
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BehaviorRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The space property</summary>
        public global::ApiSdk.Api.Behavior.Space.SpaceRequestBuilder Space
        {
            get => new global::ApiSdk.Api.Behavior.Space.SpaceRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Api.Behavior.BehaviorRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BehaviorRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/behavior", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Api.Behavior.BehaviorRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BehaviorRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/behavior", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
