/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { SpaceRequestBuilderRequestsMetadata, type SpaceRequestBuilder } from './space/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/behavior
 */
export interface BehaviorRequestBuilder extends BaseRequestBuilder<BehaviorRequestBuilder> {
    /**
     * The space property
     */
    get space(): SpaceRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const BehaviorRequestBuilderUriTemplate = "{+baseurl}/api/behavior";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const BehaviorRequestBuilderNavigationMetadata: Record<Exclude<keyof BehaviorRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    space: {
        requestsMetadata: SpaceRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
