/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type Guid, type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

export interface BehaviorEvent extends AdditionalDataHolder, Parsable {
    /**
     * Event action
     */
    action?: string | null;
    /**
     * Event actor
     */
    actor?: string | null;
    /**
     * Additional metadata
     */
    metadata?: BehaviorEvent_metadata | null;
    /**
     * Event timestamp
     */
    timestamp?: Date | null;
}
/**
 * Additional metadata
 */
export interface BehaviorEvent_metadata extends AdditionalDataHolder, Parsable {
}
export interface CompareRequest extends AdditionalDataHolder, Parsable {
    /**
     * The events property
     */
    events?: BehaviorEvent[] | null;
    /**
     * The modelNames property
     */
    modelNames?: string[] | null;
}
export interface CompareResponse extends AdditionalDataHolder, Parsable {
    /**
     * The results property
     */
    results?: ModelComparison[] | null;
}
export interface Confidence extends AdditionalDataHolder, Parsable {
    /**
     * The level property
     */
    level?: Confidence_level | null;
    /**
     * The score property
     */
    score?: number | null;
}
export type Confidence_level = (typeof Confidence_levelObject)[keyof typeof Confidence_levelObject];
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {BehaviorEvent_metadata}
 */
// @ts-ignore
export function createBehaviorEvent_metadataFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoBehaviorEvent_metadata;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {BehaviorEvent}
 */
// @ts-ignore
export function createBehaviorEventFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoBehaviorEvent;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CompareRequest}
 */
// @ts-ignore
export function createCompareRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCompareRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CompareResponse}
 */
// @ts-ignore
export function createCompareResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCompareResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Confidence}
 */
// @ts-ignore
export function createConfidenceFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoConfidence;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CreateSpaceRequest}
 */
// @ts-ignore
export function createCreateSpaceRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreateSpaceRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ErrorResponse}
 */
// @ts-ignore
export function createErrorResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoErrorResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {EvaluateRequest}
 */
// @ts-ignore
export function createEvaluateRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoEvaluateRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {EvaluateResponse}
 */
// @ts-ignore
export function createEvaluateResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoEvaluateResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ExplainNode}
 */
// @ts-ignore
export function createExplainNodeFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoExplainNode;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ExplainRequest}
 */
// @ts-ignore
export function createExplainRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoExplainRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ExplainResponse}
 */
// @ts-ignore
export function createExplainResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoExplainResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {InferRequest}
 */
// @ts-ignore
export function createInferRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoInferRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {InferResponse}
 */
// @ts-ignore
export function createInferResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoInferResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Intent}
 */
// @ts-ignore
export function createIntentFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoIntent;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ModelComparison}
 */
// @ts-ignore
export function createModelComparisonFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoModelComparison;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Policy}
 */
// @ts-ignore
export function createPolicyFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPolicy;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PolicyRule}
 */
// @ts-ignore
export function createPolicyRuleFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPolicyRule;
}
export interface CreateSpaceRequest extends AdditionalDataHolder, Parsable {
    /**
     * The events property
     */
    events?: BehaviorEvent[] | null;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SpaceResponse_vector}
 */
// @ts-ignore
export function createSpaceResponse_vectorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSpaceResponse_vector;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SpaceResponse}
 */
// @ts-ignore
export function createSpaceResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSpaceResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {TimelineEntry}
 */
// @ts-ignore
export function createTimelineEntryFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoTimelineEntry;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {TimelineResponse}
 */
// @ts-ignore
export function createTimelineResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoTimelineResponse;
}
/**
 * The deserialization information for the current model
 * @param BehaviorEvent The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoBehaviorEvent(behaviorEvent: Partial<BehaviorEvent> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "action": n => { behaviorEvent.action = n.getStringValue(); },
        "actor": n => { behaviorEvent.actor = n.getStringValue(); },
        "metadata": n => { behaviorEvent.metadata = n.getObjectValue<BehaviorEvent_metadata>(createBehaviorEvent_metadataFromDiscriminatorValue); },
        "timestamp": n => { behaviorEvent.timestamp = n.getDateValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param BehaviorEvent_metadata The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoBehaviorEvent_metadata(behaviorEvent_metadata: Partial<BehaviorEvent_metadata> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @param CompareRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCompareRequest(compareRequest: Partial<CompareRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "events": n => { compareRequest.events = n.getCollectionOfObjectValues<BehaviorEvent>(createBehaviorEventFromDiscriminatorValue); },
        "modelNames": n => { compareRequest.modelNames = n.getCollectionOfPrimitiveValues<string>("string"); },
    }
}
/**
 * The deserialization information for the current model
 * @param CompareResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCompareResponse(compareResponse: Partial<CompareResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "results": n => { compareResponse.results = n.getCollectionOfObjectValues<ModelComparison>(createModelComparisonFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param Confidence The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoConfidence(confidence: Partial<Confidence> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "level": n => { confidence.level = n.getEnumValue<Confidence_level>(Confidence_levelObject); },
        "score": n => { confidence.score = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param CreateSpaceRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCreateSpaceRequest(createSpaceRequest: Partial<CreateSpaceRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "events": n => { createSpaceRequest.events = n.getCollectionOfObjectValues<BehaviorEvent>(createBehaviorEventFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param ErrorResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoErrorResponse(errorResponse: Partial<ErrorResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "code": n => { errorResponse.code = n.getStringValue(); },
        "message": n => { errorResponse.messageEscaped = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param EvaluateRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoEvaluateRequest(evaluateRequest: Partial<EvaluateRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "intent": n => { evaluateRequest.intent = n.getObjectValue<Intent>(createIntentFromDiscriminatorValue); },
        "policy": n => { evaluateRequest.policy = n.getObjectValue<Policy>(createPolicyFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param EvaluateResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoEvaluateResponse(evaluateResponse: Partial<EvaluateResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "decision": n => { evaluateResponse.decision = n.getEnumValue<EvaluateResponse_decision>(EvaluateResponse_decisionObject); },
    }
}
/**
 * The deserialization information for the current model
 * @param ExplainNode The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoExplainNode(explainNode: Partial<ExplainNode> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "children": n => { explainNode.children = n.getCollectionOfObjectValues<ExplainNode>(createExplainNodeFromDiscriminatorValue); },
        "confidence": n => { explainNode.confidence = n.getNumberValue(); },
        "label": n => { explainNode.label = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ExplainRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoExplainRequest(explainRequest: Partial<ExplainRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "intent": n => { explainRequest.intent = n.getObjectValue<Intent>(createIntentFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param ExplainResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoExplainResponse(explainResponse: Partial<ExplainResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "root": n => { explainResponse.root = n.getObjectValue<ExplainNode>(createExplainNodeFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param InferRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoInferRequest(inferRequest: Partial<InferRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "events": n => { inferRequest.events = n.getCollectionOfObjectValues<BehaviorEvent>(createBehaviorEventFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param InferResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoInferResponse(inferResponse: Partial<InferResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "confidence": n => { inferResponse.confidence = n.getObjectValue<Confidence>(createConfidenceFromDiscriminatorValue); },
        "name": n => { inferResponse.name = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param Intent The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoIntent(intent: Partial<Intent> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "confidence": n => { intent.confidence = n.getObjectValue<Confidence>(createConfidenceFromDiscriminatorValue); },
        "name": n => { intent.name = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ModelComparison The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoModelComparison(modelComparison: Partial<ModelComparison> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "elapsedMs": n => { modelComparison.elapsedMs = n.getNumberValue(); },
        "intent": n => { modelComparison.intent = n.getObjectValue<Intent>(createIntentFromDiscriminatorValue); },
        "modelName": n => { modelComparison.modelName = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param Policy The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPolicy(policy: Partial<Policy> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "rules": n => { policy.rules = n.getCollectionOfObjectValues<PolicyRule>(createPolicyRuleFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param PolicyRule The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPolicyRule(policyRule: Partial<PolicyRule> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "decision": n => { policyRule.decision = n.getEnumValue<PolicyRule_decision>(PolicyRule_decisionObject); },
        "name": n => { policyRule.name = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param SpaceResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSpaceResponse(spaceResponse: Partial<SpaceResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "eventCount": n => { spaceResponse.eventCount = n.getNumberValue(); },
        "id": n => { spaceResponse.id = n.getGuidValue(); },
        "vector": n => { spaceResponse.vector = n.getObjectValue<SpaceResponse_vector>(createSpaceResponse_vectorFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param SpaceResponse_vector The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSpaceResponse_vector(spaceResponse_vector: Partial<SpaceResponse_vector> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @param TimelineEntry The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoTimelineEntry(timelineEntry: Partial<TimelineEntry> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "confidence": n => { timelineEntry.confidence = n.getObjectValue<Confidence>(createConfidenceFromDiscriminatorValue); },
        "decision": n => { timelineEntry.decision = n.getStringValue(); },
        "intentName": n => { timelineEntry.intentName = n.getStringValue(); },
        "timestamp": n => { timelineEntry.timestamp = n.getDateValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param TimelineResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoTimelineResponse(timelineResponse: Partial<TimelineResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "entityId": n => { timelineResponse.entityId = n.getStringValue(); },
        "entries": n => { timelineResponse.entries = n.getCollectionOfObjectValues<TimelineEntry>(createTimelineEntryFromDiscriminatorValue); },
    }
}
export interface ErrorResponse extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The code property
     */
    code?: string | null;
    /**
     * The message property
     */
    messageEscaped?: string | null;
}
export interface EvaluateRequest extends AdditionalDataHolder, Parsable {
    /**
     * The intent property
     */
    intent?: Intent | null;
    /**
     * The policy property
     */
    policy?: Policy | null;
}
export interface EvaluateResponse extends AdditionalDataHolder, Parsable {
    /**
     * The decision property
     */
    decision?: EvaluateResponse_decision | null;
}
export type EvaluateResponse_decision = (typeof EvaluateResponse_decisionObject)[keyof typeof EvaluateResponse_decisionObject];
export interface ExplainNode extends AdditionalDataHolder, Parsable {
    /**
     * The children property
     */
    children?: ExplainNode[] | null;
    /**
     * The confidence property
     */
    confidence?: number | null;
    /**
     * The label property
     */
    label?: string | null;
}
export interface ExplainRequest extends AdditionalDataHolder, Parsable {
    /**
     * The intent property
     */
    intent?: Intent | null;
}
export interface ExplainResponse extends AdditionalDataHolder, Parsable {
    /**
     * The root property
     */
    root?: ExplainNode | null;
}
export interface InferRequest extends AdditionalDataHolder, Parsable {
    /**
     * The events property
     */
    events?: BehaviorEvent[] | null;
}
export interface InferResponse extends AdditionalDataHolder, Parsable {
    /**
     * The confidence property
     */
    confidence?: Confidence | null;
    /**
     * Intent name
     */
    name?: string | null;
}
export interface Intent extends AdditionalDataHolder, Parsable {
    /**
     * The confidence property
     */
    confidence?: Confidence | null;
    /**
     * The name property
     */
    name?: string | null;
}
export interface ModelComparison extends AdditionalDataHolder, Parsable {
    /**
     * The elapsedMs property
     */
    elapsedMs?: number | null;
    /**
     * The intent property
     */
    intent?: Intent | null;
    /**
     * The modelName property
     */
    modelName?: string | null;
}
export interface Policy extends AdditionalDataHolder, Parsable {
    /**
     * The rules property
     */
    rules?: PolicyRule[] | null;
}
export interface PolicyRule extends AdditionalDataHolder, Parsable {
    /**
     * The decision property
     */
    decision?: PolicyRule_decision | null;
    /**
     * The name property
     */
    name?: string | null;
}
export type PolicyRule_decision = (typeof PolicyRule_decisionObject)[keyof typeof PolicyRule_decisionObject];
/**
 * Serializes information the current object
 * @param BehaviorEvent The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeBehaviorEvent(writer: SerializationWriter, behaviorEvent: Partial<BehaviorEvent> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!behaviorEvent || isSerializingDerivedType) { return; }
    writer.writeStringValue("action", behaviorEvent.action);
    writer.writeStringValue("actor", behaviorEvent.actor);
    writer.writeObjectValue<BehaviorEvent_metadata>("metadata", behaviorEvent.metadata, serializeBehaviorEvent_metadata);
    writer.writeDateValue("timestamp", behaviorEvent.timestamp);
    writer.writeAdditionalData(behaviorEvent.additionalData);
}
/**
 * Serializes information the current object
 * @param BehaviorEvent_metadata The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeBehaviorEvent_metadata(writer: SerializationWriter, behaviorEvent_metadata: Partial<BehaviorEvent_metadata> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!behaviorEvent_metadata || isSerializingDerivedType) { return; }
    writer.writeAdditionalData(behaviorEvent_metadata.additionalData);
}
/**
 * Serializes information the current object
 * @param CompareRequest The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCompareRequest(writer: SerializationWriter, compareRequest: Partial<CompareRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!compareRequest || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<BehaviorEvent>("events", compareRequest.events, serializeBehaviorEvent);
    writer.writeCollectionOfPrimitiveValues<string>("modelNames", compareRequest.modelNames);
    writer.writeAdditionalData(compareRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param CompareResponse The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCompareResponse(writer: SerializationWriter, compareResponse: Partial<CompareResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!compareResponse || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<ModelComparison>("results", compareResponse.results, serializeModelComparison);
    writer.writeAdditionalData(compareResponse.additionalData);
}
/**
 * Serializes information the current object
 * @param Confidence The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeConfidence(writer: SerializationWriter, confidence: Partial<Confidence> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!confidence || isSerializingDerivedType) { return; }
    writer.writeEnumValue<Confidence_level>("level", confidence.level);
    writer.writeNumberValue("score", confidence.score);
    writer.writeAdditionalData(confidence.additionalData);
}
/**
 * Serializes information the current object
 * @param CreateSpaceRequest The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCreateSpaceRequest(writer: SerializationWriter, createSpaceRequest: Partial<CreateSpaceRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!createSpaceRequest || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<BehaviorEvent>("events", createSpaceRequest.events, serializeBehaviorEvent);
    writer.writeAdditionalData(createSpaceRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param ErrorResponse The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeErrorResponse(writer: SerializationWriter, errorResponse: Partial<ErrorResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!errorResponse || isSerializingDerivedType) { return; }
    writer.writeStringValue("code", errorResponse.code);
    writer.writeStringValue("message", errorResponse.messageEscaped);
    writer.writeAdditionalData(errorResponse.additionalData);
}
/**
 * Serializes information the current object
 * @param EvaluateRequest The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeEvaluateRequest(writer: SerializationWriter, evaluateRequest: Partial<EvaluateRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!evaluateRequest || isSerializingDerivedType) { return; }
    writer.writeObjectValue<Intent>("intent", evaluateRequest.intent, serializeIntent);
    writer.writeObjectValue<Policy>("policy", evaluateRequest.policy, serializePolicy);
    writer.writeAdditionalData(evaluateRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param EvaluateResponse The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeEvaluateResponse(writer: SerializationWriter, evaluateResponse: Partial<EvaluateResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!evaluateResponse || isSerializingDerivedType) { return; }
    writer.writeEnumValue<EvaluateResponse_decision>("decision", evaluateResponse.decision);
    writer.writeAdditionalData(evaluateResponse.additionalData);
}
/**
 * Serializes information the current object
 * @param ExplainNode The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeExplainNode(writer: SerializationWriter, explainNode: Partial<ExplainNode> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!explainNode || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<ExplainNode>("children", explainNode.children, serializeExplainNode);
    writer.writeNumberValue("confidence", explainNode.confidence);
    writer.writeStringValue("label", explainNode.label);
    writer.writeAdditionalData(explainNode.additionalData);
}
/**
 * Serializes information the current object
 * @param ExplainRequest The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeExplainRequest(writer: SerializationWriter, explainRequest: Partial<ExplainRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!explainRequest || isSerializingDerivedType) { return; }
    writer.writeObjectValue<Intent>("intent", explainRequest.intent, serializeIntent);
    writer.writeAdditionalData(explainRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param ExplainResponse The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeExplainResponse(writer: SerializationWriter, explainResponse: Partial<ExplainResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!explainResponse || isSerializingDerivedType) { return; }
    writer.writeObjectValue<ExplainNode>("root", explainResponse.root, serializeExplainNode);
    writer.writeAdditionalData(explainResponse.additionalData);
}
/**
 * Serializes information the current object
 * @param InferRequest The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeInferRequest(writer: SerializationWriter, inferRequest: Partial<InferRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!inferRequest || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<BehaviorEvent>("events", inferRequest.events, serializeBehaviorEvent);
    writer.writeAdditionalData(inferRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param InferResponse The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeInferResponse(writer: SerializationWriter, inferResponse: Partial<InferResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!inferResponse || isSerializingDerivedType) { return; }
    writer.writeObjectValue<Confidence>("confidence", inferResponse.confidence, serializeConfidence);
    writer.writeStringValue("name", inferResponse.name);
    writer.writeAdditionalData(inferResponse.additionalData);
}
/**
 * Serializes information the current object
 * @param Intent The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeIntent(writer: SerializationWriter, intent: Partial<Intent> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!intent || isSerializingDerivedType) { return; }
    writer.writeObjectValue<Confidence>("confidence", intent.confidence, serializeConfidence);
    writer.writeStringValue("name", intent.name);
    writer.writeAdditionalData(intent.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param ModelComparison The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeModelComparison(writer: SerializationWriter, modelComparison: Partial<ModelComparison> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!modelComparison || isSerializingDerivedType) { return; }
    writer.writeNumberValue("elapsedMs", modelComparison.elapsedMs);
    writer.writeObjectValue<Intent>("intent", modelComparison.intent, serializeIntent);
    writer.writeStringValue("modelName", modelComparison.modelName);
    writer.writeAdditionalData(modelComparison.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param Policy The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePolicy(writer: SerializationWriter, policy: Partial<Policy> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!policy || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<PolicyRule>("rules", policy.rules, serializePolicyRule);
    writer.writeAdditionalData(policy.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param PolicyRule The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePolicyRule(writer: SerializationWriter, policyRule: Partial<PolicyRule> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!policyRule || isSerializingDerivedType) { return; }
    writer.writeEnumValue<PolicyRule_decision>("decision", policyRule.decision);
    writer.writeStringValue("name", policyRule.name);
    writer.writeAdditionalData(policyRule.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param SpaceResponse The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSpaceResponse(writer: SerializationWriter, spaceResponse: Partial<SpaceResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!spaceResponse || isSerializingDerivedType) { return; }
    writer.writeNumberValue("eventCount", spaceResponse.eventCount);
    writer.writeGuidValue("id", spaceResponse.id);
    writer.writeObjectValue<SpaceResponse_vector>("vector", spaceResponse.vector, serializeSpaceResponse_vector);
    writer.writeAdditionalData(spaceResponse.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param SpaceResponse_vector The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSpaceResponse_vector(writer: SerializationWriter, spaceResponse_vector: Partial<SpaceResponse_vector> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!spaceResponse_vector || isSerializingDerivedType) { return; }
    writer.writeAdditionalData(spaceResponse_vector.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param TimelineEntry The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeTimelineEntry(writer: SerializationWriter, timelineEntry: Partial<TimelineEntry> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!timelineEntry || isSerializingDerivedType) { return; }
    writer.writeObjectValue<Confidence>("confidence", timelineEntry.confidence, serializeConfidence);
    writer.writeStringValue("decision", timelineEntry.decision);
    writer.writeStringValue("intentName", timelineEntry.intentName);
    writer.writeDateValue("timestamp", timelineEntry.timestamp);
    writer.writeAdditionalData(timelineEntry.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param TimelineResponse The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeTimelineResponse(writer: SerializationWriter, timelineResponse: Partial<TimelineResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!timelineResponse || isSerializingDerivedType) { return; }
    writer.writeStringValue("entityId", timelineResponse.entityId);
    writer.writeCollectionOfObjectValues<TimelineEntry>("entries", timelineResponse.entries, serializeTimelineEntry);
    writer.writeAdditionalData(timelineResponse.additionalData);
}
export interface SpaceResponse extends AdditionalDataHolder, Parsable {
    /**
     * The eventCount property
     */
    eventCount?: number | null;
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The vector property
     */
    vector?: SpaceResponse_vector | null;
}
export interface SpaceResponse_vector extends AdditionalDataHolder, Parsable {
}
export interface TimelineEntry extends AdditionalDataHolder, Parsable {
    /**
     * The confidence property
     */
    confidence?: Confidence | null;
    /**
     * The decision property
     */
    decision?: string | null;
    /**
     * The intentName property
     */
    intentName?: string | null;
    /**
     * The timestamp property
     */
    timestamp?: Date | null;
}
export interface TimelineResponse extends AdditionalDataHolder, Parsable {
    /**
     * The entityId property
     */
    entityId?: string | null;
    /**
     * The entries property
     */
    entries?: TimelineEntry[] | null;
}
export const Confidence_levelObject = {
    Certain: "Certain",
    High: "High",
    Medium: "Medium",
    Low: "Low",
} as const;
export const EvaluateResponse_decisionObject = {
    Allow: "Allow",
    Observe: "Observe",
    Warn: "Warn",
    Block: "Block",
    Escalate: "Escalate",
    RequireAuth: "RequireAuth",
    RateLimit: "RateLimit",
} as const;
export const PolicyRule_decisionObject = {
    Allow: "Allow",
    Observe: "Observe",
    Warn: "Warn",
    Block: "Block",
    Escalate: "Escalate",
    RequireAuth: "RequireAuth",
    RateLimit: "RateLimit",
} as const;
/* tslint:enable */
/* eslint-enable */
