/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createSpaceResponseFromDiscriminatorValue, serializeCreateSpaceRequest, serializeSpaceResponse, type CreateSpaceRequest, type SpaceResponse } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/behavior/space
 */
export interface SpaceRequestBuilder extends BaseRequestBuilder<SpaceRequestBuilder> {
    /**
     * Create behavior space from events
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SpaceResponse>}
     */
     post(body: CreateSpaceRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<SpaceResponse | undefined>;
    /**
     * Create behavior space from events
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: CreateSpaceRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const SpaceRequestBuilderUriTemplate = "{+baseurl}/api/behavior/space";
/**
 * Metadata for all the requests in the request builder.
 */
export const SpaceRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: SpaceRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createSpaceResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeCreateSpaceRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
