/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createErrorResponseFromDiscriminatorValue, createInferResponseFromDiscriminatorValue, serializeInferRequest, serializeInferResponse, type ErrorResponse, type InferRequest, type InferResponse } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/intent/infer
 */
export interface InferRequestBuilder extends BaseRequestBuilder<InferRequestBuilder> {
    /**
     * Infer intent from behavior events
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<InferResponse>}
     * @throws {ErrorResponse} error when the service returns a 400 status code
     */
     post(body: InferRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<InferResponse | undefined>;
    /**
     * Infer intent from behavior events
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: InferRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const InferRequestBuilderUriTemplate = "{+baseurl}/api/intent/infer";
/**
 * Metadata for all the requests in the request builder.
 */
export const InferRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: InferRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createInferResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeInferRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
